### ISSUE TITLE
2018 年终总结

### ISSUE THREAD

**Issue by ahonn** [ahonn/blog#49]
一眨眼 8102 年都快结束了，年终总结也拖了好几天。今天晚上终于可以静下心来写一写了。

先看一下去年立下的 KPI 完成了多少...

## 2018 checklist

- [x] 跟女朋友在杭州工作生活能够顺顺利利
- [x] 好好赚钱，减轻父母压力，照顾好弟弟
- [ ] 努力工作，在技术上能够更上一层楼
- [x] 除了读技术书籍之外，读多一些其他书 (假装完成)
- [x] 拓展一下兴趣爱好，学会做饭 (学会了一点点)
- [ ] 多运动，多健身，避免久坐

很明显，去年年底聪明的立了一些稍微容易实现的 Flag，导致今年的完成度很高。今年照例还是会为新的一年写个清单，希望未来的一年能够朝着目标前进（当然，肯定是无法百分百完成）。

```js
const checklist = [];
```

## 又一次来到杭州

![飞机窗外](http://ahonn-me.oss-cn-beijing.aliyuncs.com/images/8vt9q.jpg)

又一次，不同的是这一次来杭州不是短暂的实习了，而是可能是好几年的工作生活。而且这次的飞机没有延误了，天气也异常的好。

算了算，在杭州也快呆了快一年了，然而除了西湖 & 西湖附近之外没有去过其他地方，有点失败。主要原因还是工作了五天，每到周末都想要有时间可以好好在家里宅着。反观我女朋友就不一样了，一到周末就想着去哪里浪。要不是她，估计我连西湖都懒得去，大部分周末都会被她拉出去逛。不过逛来逛去都是那几个地方，明年要好好熟悉熟悉杭州了，多发掘一些杭州没有去过多地方。

```js
checklist.push('多出去不同多地方逛逛');
```

## 一年胖十斤

去年来杭州的我体重只有  63 KG，今年的我已经飙升到 68 KG 了。相信再过不久就要到达 70 KG 了，很快就会变成正在的女朋友口中的 “肥江” 了。可能是工作之后长期久坐造成了脂肪堆积，这一年将近胖了 10 斤，真的是肥胖抹平了我的“棱角”（脸都没有棱角了，我女朋友如是说）。所以新的一年还是要多多运动的，虽然去年也是这样说的，而且并没有做到。但是今年依旧还是得继续让明年的自己记得这件事，不能继续再长胖了。

```js
checklist.push('多运动，少久坐，保持体重');
```

##  学点其他技能

这一年开始自己做饭了，出门再外总是要吃饭的，不自己做总不能靠着外卖过活吧？所以自然的去年的 KPI 里包含里学会做饭这一项。今年也大概算是完成啦这个目标。学会了做一些菜，勉强还是可以吃的。最拿手的就是咖喱饭 & 酒煮花甲了，虽然这两个菜比较简单，但是我自己倒是觉得做得还蛮好吃的。

不过还是不太喜欢去买菜，后面半年搬到了一个盒马配送能到的地方，简直幸福。做菜愉快多了，当然洗碗依旧是很烦的啊。

年底的时候突然对 Vlog 很感兴趣，尝试拍了几次，但是都不满意，对视频剪辑也是一窍不通。希望来年能够学一学这一方面的东西，剪出一些自己喜欢的片子。一方面是让自己学一门技能，一方面是让生活变得更有味道。等什么时候有钱 & 下定决心了就买一个 Go Pro 来玩玩。

```js
checklist.push('学习视频拍摄&剪辑，发一些 Vlog');
```

## 书还要继续读

去年为了校招看了很多的技术方面的书籍，于是计划着今年要读多些其他的书。但貌似是没有做到..

今年读过的书（包括没有读完）：

* [东方快车谋杀案](https://www.douban.com/link2/?url=https%3A%2F%2Fbook.douban.com%2Fsubject%2F24153048%2F&query=%E4%B8%9C%E6%96%B9%E5%BF%AB%E8%BD%A6%E8%B0%8B%E6%9D%80%E6%A1%88&cat_id=1001&type=search&pos=1)
* [贫穷的本质](https://www.douban.com/link2/?url=https%3A%2F%2Fbook.douban.com%2Fsubject%2F21966353%2F&query=%E8%B4%AB%E7%A9%B7%E7%9A%84%E6%9C%AC%E8%B4%A8&cat_id=1001&type=search&pos=0)（未读完）
* [牛奶可乐经济学](https://www.douban.com/link2/?url=https%3A%2F%2Fbook.douban.com%2Fsubject%2F3000997%2F&query=%E7%89%9B%E5%A5%B6%E5%8F%AF%E4%B9%90%E7%BB%8F%E6%B5%8E&cat_id=1001&type=search&pos=0)（未读完）
* [24 个比利](https://www.douban.com/link2/?url=https%3A%2F%2Fbook.douban.com%2Fsubject%2F26371317%2F&query=24%E4%B8%AA%E6%AF%94%E5%88%A9&cat_id=1001&type=search&pos=0)
* [深入浅出 Rxjs](https://www.douban.com/link2/?url=https%3A%2F%2Fbook.douban.com%2Fsubject%2F30217949%2F&query=%E6%B7%B1%E5%85%A5%E6%B5%85%E5%87%BA+Rxjs&cat_id=1001&type=search&pos=0)
* [Haskell 趣学指南](https://www.douban.com/link2/?url=https%3A%2F%2Fbook.douban.com%2Fsubject%2F25803388%2F&query=Haskell+%E8%B6%A3%E5%AD%A6%E6%8C%87%E5%8D%97&cat_id=1001&type=search&pos=0)（未读完）
* [JavaScript 函数式编程指南](https://legacy.gitbook.com/book/llh911001/mostly-adequate-guide-chinese/details)

与实际中的预想有些偏差，有三本书读到一半就没有继续读了。主要还是因为搬家打乱了原先上班路上看书读节奏（借口），有一段时间基本上都没有怎么看书。直到年末的时候看了本《24 个比利》，读完这本书的感受就是也许每个人的心里都会有不同的“比利”存在，也许只是我们没有发现而已。也许大学之前的我其实是另一个我？

多读些非技术书籍的目标没有实现，大部分还是看技术相关的居多。新的一年依旧是要继续看书的，但是这次的目标不一样了。

2019 年希望自己能够多看几本英文原版书籍，从简单的慢慢看起。至于看什么类型的书，随缘好了。为什么会有这种想法呢？因为好多时候想看的书都是英文的，而自己的英语阅读能力比较差，便成了想看而无法看的境地。所以先挑一个软柿子捏，决定了就是哈利波特了，祝自己好运～

```js
checklist.push('多阅读，尝试读一些英文原版书籍');
```

## 博客几乎没有写

个人博客在这一年几乎是废弃的。到目前为止，包括这一篇年终总结，今年的博客文章总共就三篇。另外的两篇分别是读书笔记和踩坑总结。

个人在技术上基本上都没有输出，惭愧惭愧。新的一年一定要重新写起来。实际上，这一年在业余时间也是接触了一些新技术的，WebAssembly，Web Components 之类的。但是基本都没有太过深入，后续如果有深入的话一定要输出一些文章出来（又立 Flag）。

今年的博客日PV：

![博客日PV](http://ahonn-me.oss-cn-beijing.aliyuncs.com/images/c8g7c.png)

理所应当的数据很惨淡，毕竟只能依靠着去年的老文章过活。给明年的自己定一个可量化的目标：博客的日平均 PV 达到 500 人次。

```js
checklist.push('多写文章，目标博客日平均 PV 500');
```

## 没有 Side Project

照例，总结里头是少不了 Github 的 contributions 图的：

![github](http://ahonn-me.oss-cn-beijing.aliyuncs.com/images/kikzc.png)

但基本上是没有什么业余的个人项目了，博客主题也少有维护了。主要一个还是太忙，下班完完全是不想碰电脑的。这样其实不太好，业余没有积累的话就会越来越没有竞争力的。大部分的 commit 都是修改 [dotfiles](https://github.com/ahonn/dotfiles)，毕竟这个是我每天都会使用的。至于明年，肯定是不能跟今年一样懈怠的。准备写一写自己常用的一些工具软件，例如造一个 TODO APP 之类的，具体没有想好。目标是能够学一些新东西运用起来。

```js
checklist.push('用新技术造一些自己常用的工具软件');
```

## 工作是要解决问题

正式工作之后，发现和自己原来想象的不太一样。并不是大公司里面的员工技术就强，而是他们都能够去解决问题，不限于通过技术手段解决。技术只是解决问题的一个手段，一个辅助。更多时候需要能够去解决问题，而不是要技术有多么的强。

今年在工作上对某些技术之外的处理还有欠妥，给别人造成了不必要的麻烦。虽然是新人，但其实也应该去尝试 hold 住。这让我意识到软实力也很重要，所以今年的目标之一是能够在工作中更加从容的去解决问题，多学习一些软技能。如何去与人更好的沟通，如何去推动其他人一起把问题解决，如何在逆境中更好的处理事情。这些都是未来要好好学习的。

即使是程序猿，也不应该只把自己局限在这之内。Developer === Resolver

来年要把该做的工作都做好，并且尽量能够做超出预期，软硬兼顾。

```js
checklist.push('更好的完成工作，软硬兼顾');
```

## // TODO: 2019

到这里，2018 年的总结就差不多写完了。列一下上面为明年定下了那些 KPI：

```js
console.log(checklist);
```

- 多出去不同多地方逛逛
- 多运动，少久坐，保持体重
- 学习视频拍摄&剪辑，发一些 Vlog
- 多阅读，尝试读一些英文原版书籍
- 多写文章，目标博客日平均 PV 500
- 用新技术造一些自己常用的工具软件
- 更好的完成工作，软硬兼顾

看起来差不多了，当然理论上是不存在全部完成的。最后加上一条一定要完成的 KPI：

```js
checklist.push('与女朋友一起好好生活');
```

Keep learning & Happy life ...

**Comment by ahonn** [comment]
测试
